function [] = saveRS(outFile,totalerr,miss,extra,reverse,missorient,correct,runtime,lEdge,GEdge,cEdge,P,R,F1,P_pie,R_pie,F1_pie,i)
ran = 17;
str1 = {'Extra'};
table1 = table(str1);
range1 = 'A'+string(ran*(i-1)+1);
writetable(table1,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range1);
str2 = {'Miss'};
table2 = table(str2);
range2 = 'A'+string(ran*(i-1)+2);
writetable(table2,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range2);
str3 = {'Missorient'};
table3 = table(str3);
range3 = 'A'+string(ran*(i-1)+3);
writetable(table3,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range3);
str4 = {'Reverse'};
table4 = table(str4);
range4 = 'A'+string(ran*(i-1)+4);
writetable(table4,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range4);
str5 = {'Totalerr'};
table5 = table(str5);
range5 = 'A'+string(ran*(i-1)+5);
writetable(table5,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range5);
str6 = {'Correct'};
table6 = table(str6);
range6 = 'A'+string(ran*(i-1)+6);
writetable(table6,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range6);
str7 = {'P'};
table7 = table(str7);
range7 = 'A'+string(ran*(i-1)+7);
writetable(table7,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range7);
str8 = {'Recall'};
table8 = table(str8);
range8 = 'A'+string(ran*(i-1)+8);
writetable(table8,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range8);
str9 = {'F1'};
table9 = table(str9);
range9 = 'A'+string(ran*(i-1)+9);
writetable(table9,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range9);
str10 = {'RunningTime'};
table10 = table(str10);
range10 = 'A'+string(ran*(i-1)+10);
writetable(table10,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range10);
str11 = {'Learned Edge'};
table11 = table(str11);
range11 = 'A'+string(ran*(i-1)+11);
writetable(table11,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range11);
str12_ = {'Real Edge'};
table12_ = table(str12_);
range12_ = 'A'+string(ran*(i-1)+12);
writetable(table12_,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range12_);
str13 = {'Edges'};
table13 = table(str13);
range13 = 'A'+string(ran*(i-1)+13);
writetable(table13,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range13);
str14 = {'P_Edge'};
table14 = table(str14);
range14 = 'A'+string(ran*(i-1)+14);
writetable(table14,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range14);
str15 = {'Recal_Edge'};
table15 = table(str15);
range15 = 'A'+string(ran*(i-1)+15);
writetable(table15,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range15);
str16 = {'F1_Edge'};
table16 = table(str16);
range16 = 'A'+string(ran*(i-1)+16);
writetable(table16,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range16);



table12 = table(extra);
range12 = 'B'+string(ran*(i-1)+1);
writetable(table12,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range12);
table22 = table(miss);
range22 = 'B'+string(ran*(i-1)+2);
writetable(table22,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range22);
table32 = table(missorient);
range32 = 'B'+string(ran*(i-1)+3);
writetable(table32,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range32);
table42 = table(reverse);
range42 = 'B'+string(ran*(i-1)+4);
writetable(table42,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range42);
table52 = table(totalerr);
range52 = 'B'+string(ran*(i-1)+5);
writetable(table52,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range52);
table62 = table(correct);
range62 = 'B'+string(ran*(i-1)+6);
writetable(table62,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range62);
table72 = table(P);
range72 = 'B'+string(ran*(i-1)+7);
writetable(table72,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range72);
table82 = table(R);
range82 = 'B'+string(ran*(i-1)+8);
writetable(table82,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range82);
table92 = table(F1);
range92 = 'B'+string(ran*(i-1)+9);
writetable(table92,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range92);
table102 = table(runtime);
range102 = 'B'+string(ran*(i-1)+10);
writetable(table102,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range102);
table112 = table(lEdge);
range112 = 'B'+string(ran*(i-1)+11);
writetable(table112,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range112);
table12_2 = table(GEdge);
range12_2 = 'B'+string(ran*(i-1)+12);
writetable(table12_2,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range12_2);
table132 = table(cEdge);
range132 = 'B'+string(ran*(i-1)+13);
writetable(table132,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range132);
table142 = table(P_pie);
range142 = 'B'+string(ran*(i-1)+14);
writetable(table142,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range142);
table152 = table(R_pie);
range152 = 'B'+string(ran*(i-1)+15);
writetable(table152,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range152);
table162 = table(F1_pie);
range162 = 'B'+string(ran*(i-1)+16);
writetable(table162,outFile,'WriteVariableNames',false,'Sheet','Sheet1','Range',range162);
end